---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install PHP'
     apt:
      name: 
       - 'php'
       - 'php-fpm'
      state: 'present'
     become: yes 
   - name: 'Install nginx'
     apt:
       name: 
        - 'nginx'
        - 'mysql-server'
        - 'zip'
       state: 'present'
       update_cache: true
     become: yes
   

