---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install Python'
     apt:
      name: 
       - 'python3-pip'
       - 'python3'
      state: 'present'   
     become: yes
   - name: 'Install nginx'
     apt:
       name: 
        - 'nginx'
        - 'mysql-server'
        - 'zip'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Install Wordpress'
     unarchive:
       src: 'https://wordpress.org/latest.zip'
       dest: '/var/www/'
       remote_src: true
     become: yes
   - name: 'Set mysql root password'
     mysql_user: 
       name: 'root'
       password: 'Password123'
     become: yes


