---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install PHP'
     apt:
      name: 
       - 'php'
       - 'php-fpm'
      state: 'present'
     become: yes 
   - name: 'Install nginx'
     apt:
       name: 
        - 'nginx'
        - 'mysql-server'
        - 'zip'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Download and Install Wordpress'
     unarchive:
       src: 'https://wordpress.org/latest.zip'
       dest: '/var/www'
       remote_src: true
     become: yes
   - name: 'Set mysql user password'
       mysql_user:
         name: 'root'
         password: 'DAMAitd1024'
   - name: 'Create wordpress DB'
       mysql_db:
         name: 'wordpress'      
         state: 'present'
         login_user: 'root'
         login_password: 'DAMAitd1024'


   

