---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install PHP'
     apt:
      name: 
       - 'php'
       - 'php-fpm'
      state: 'present'
     become: yes 
   - name: 'Install nginx'
     apt:
       name: 
        - 'nginx'
        - 'mysql-server'
        - 'zip'
        - 'python-pymysql'
        - 'python3-pymysql'
        - 'python-apt'
        - 'python3-apt'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Download and Install Wordpress'
     unarchive:
       src: 'https://wordpress.org/latest.zip'
       dest: '/var/www'
       remote_src: true
     become: yes
   - name: 'Set mysql user password'
     mysql_user:
       name: 'root'
       password: 'DAMAitd1024'
       login_user: 'root'
       login_password: ''
     become: yes  
   - name: 'Create wordpress DB'
     mysql_db:
       name: 'wordpress'      
       state: 'present'
       login_user: 'root'
       login_password: 'DAMAitd1024'
     become: yes


   

