---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install PHP'
     apt:
      name: 
       - 'php'
       - 'php-fpm'
      state: 'present'
     become: yes 
   
   - name: download and unpack alternative python3
     unarchive:
       src: http://www.yourmirror.com/centos/python/Python-3.6.4-binary.tar.gz dest=/tmp/Python-3.6.4-binary.tar.gz
       dest: /tmp
       remote_src: yes
       keep_newer: yes
     when: python3_version['stderr'] != 'Python 3.6.4'
     tags:
       - python-alt

   # Its possible to install (instead of altinstall) python3 here
   - name: make install alt python3
     make:
       chdir: /tmp/Python-3.6.4-binary
       target: altinstall
       params:
         UNINST: 1  # Replace
     when: python3_version['stderr'] != 'Python 3.6.4'
     become: yes
     tags:
       - python-alt

   - name: download get-pip.py
     get_url:
       url: https://bootstrap.pypa.io/get-pip.py
       dest: /tmp/get-pip.py
       mode: 0664
     tags:
       - python-alt

   - name: install pip for python3
     shell: /usr/local/bin/python3.6 /tmp/get-pip.py
     become: yes
     tags:
       - python-alt

# We need virtualenv installed under py3 for the virtualenv command to work
   - pip:
       name: virtualenv
       executable: /usr/local/bin/pip3.6
     become: True
     tags:
       - python-alt

   - name: 'Install nginx'
     apt:
       name: 
        - 'nginx'
        - 'mysql-server'
        - 'zip'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Download and Install Wordpress'
     unarchive:
       src: 'https://wordpress.org/latest.zip'
       dest: '/var/www'
       remote_src: true
     become: yes
   - name: 'Set mysql user password'
     mysql_user:
       name: 'root'
       password: 'DAMAitd1024'
       login_user: 'root'
       login_password: ''
     become: yes  
   - name: 'Create wordpress DB'
     mysql_db:
       name: 'wordpress'      
       state: 'present'
       login_user: 'root'
       login_password: 'DAMAitd1024'
     become: yes


   

