---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install PHP'
     apt:
      name: 
       - 'php'
       - 'php-fpm'
      state: 'present'
     become: yes
   - name: 'Install Python'
     apt:
       name:
        - 'python-apt'
        - 'python3-apt'
        - 'python3-mysqldb'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Install nginx'
     apt:
       name: 
        - 'nginx'
        - 'mysql-server'
        - 'zip'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Download and Install Wordpress'
     unarchive:
       src: 'https://wordpress.org/latest.zip'
       dest: '/var/www'
       remote_src: true
     become: yes
   - name: 'Set mysql root password'
     mysql_user:
       name: 'root'
       password: 'DAMAitd1024'
       login_user: 'root'
       login_password: ''
     become: yes  
   - name: 'create glpi user'
     mysql_user:
       name: 'glpi'
       password: 'Niko70'
       update_password: 'on_create'
       login_user: 'root'
       login_password: 'DAMAitd1024'
     become: yes  
   - name: 'Create GLPI DB'
     mysql_db:
       name: 'glpi'      
       state: 'present'
       login_user: 'root'
       login_password: 'DAMAitd1024'
     become: yes


   

