---

- hosts: 'webservers'
  remote_user: ubuntu
  tasks: 
   - name: 'Install PHP'
     apt:
      name: 
       - 'php'
       - 'php-fpm'
       - 'php-curl'
       - 'php-gd'
       - 'php-imagick'
       - 'php-intl'
       - 'php-apcu'
       - 'php-memcache'
       - 'php-imap'
       - 'php-mysql'
       - 'php-cas'
       - 'php-ldap'
       - 'php-tidy'
       - 'php-pear'
       - 'php-xmlrpc'
       - 'php-pspell'
       - 'php-mbstring'
       - 'php-json'
       - 'php-iconv'
       - 'php-xml'
       - 'php-gd'
       - 'php-xsl'
      state: 'present'
     become: yes
   - name: 'Install Python'
     apt:
       name:
        - 'python-apt'
        - 'python3-apt'
        - 'python3-mysqldb'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Install apache2'
     apt:
       name: 
        - 'apache2'
        - 'libapache2-mod-php'
        - 'mysql-server'
        - 'zip'
       state: 'present'
       update_cache: true
     become: yes
   - name: 'Set mysql root password'
     mysql_user:
       name: 'root'
       password: 'DAMAitd1024'
       login_unix_socket: '/var/run/mysqld/mysqld.sock'
       update_password: 'on_create'
       login_user: 'root'
       login_password: 'DAMAitd1024'
     become: yes  
   - name: 'Create GLPI DB'
     mysql_db:
       name: 'glpi'      
       state: 'present'
       login_user: 'root'
       login_password: 'DAMAitd1024'
     become: yes

   - name: 'create glpi user'
     mysql_user:
       name: 'glpi'
       password: 'Niko70'
       update_password: 'on_create'
       login_user: 'root'
       login_password: 'DAMAitd1024'
       priv: 'glpi.*:ALL'
       state: 'present'
     become: yes  
   - name: 'Install GLPI'
     unarchive:
       src: 'https://github.com/glpi-project/glpi/releases/download/9.5.4/glpi-9.5.4.tgz'
       dest: '/var/www/'
       remote_src: true
     become: yes
   - name: 'Remove standart apache2 config'
     file:
       state: absent
       path: '/etc/apache2/sites-aviable/000-default.conf'
   

   

